#!/usr/bin/env python3
"""
Confluence Promotion Utility - Track manual Confluence promotions

This script helps track which session outputs have been manually promoted
to Confluence. It does NOT automatically upload - that must be done manually
to maintain control and quality.

Usage:
    promote_to_confluence.py --session SESSION_ID --file FILE_PATH --confluence-url URL

This will:
  1. Copy the output to shared/promoted-to-confluence/
  2. Create promotion metadata
  3. Update session metadata to mark output as promoted
"""

import argparse
import re
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, Optional, Tuple

try:
    import yaml
except ImportError:
    # Use simple YAML implementation
    class SimpleYAML:
        @staticmethod
        def dump(data, stream):
            """Simple YAML serializer."""
            stream.write("# Generated by promote_to_confluence.py\n")
            SimpleYAML._dump_dict(data, stream, indent=0)

        @staticmethod
        def _dump_dict(data, stream, indent):
            """Recursively dump dictionary."""
            prefix = "  " * indent
            for key, value in data.items():
                if value is None:
                    stream.write(f"{prefix}{key}: null\n")
                elif isinstance(value, bool):
                    stream.write(f"{prefix}{key}: {'true' if value else 'false'}\n")
                elif isinstance(value, (int, float)):
                    stream.write(f"{prefix}{key}: {value}\n")
                elif isinstance(value, str):
                    if '\n' in value:
                        stream.write(f"{prefix}{key}: |\n")
                        for line in value.split('\n'):
                            stream.write(f"{prefix}  {line}\n")
                    elif value == "":
                        stream.write(f'{prefix}{key}: ""\n')
                    else:
                        stream.write(f'{prefix}{key}: "{value}"\n')
                elif isinstance(value, list):
                    if not value:
                        stream.write(f"{prefix}{key}: []\n")
                    else:
                        stream.write(f"{prefix}{key}:\n")
                        for item in value:
                            if isinstance(item, dict):
                                stream.write(f"{prefix}- ")
                                first = True
                                for k, v in item.items():
                                    if not first:
                                        stream.write(f"{prefix}  ")
                                    stream.write(f'{k}: "{v}"\n')
                                    first = False
                            else:
                                stream.write(f'{prefix}- "{item}"\n')
                elif isinstance(value, dict):
                    stream.write(f"{prefix}{key}:\n")
                    SimpleYAML._dump_dict(value, stream, indent + 1)

        @staticmethod
        def safe_load(stream):
            """Basic YAML loader."""
            # This is a simplified implementation
            # For production, would use PyYAML
            data = {}
            lines = stream.readlines() if hasattr(stream, 'readlines') else stream.split('\n')
            current_key = None

            for line in lines:
                line = line.rstrip()
                if not line.strip() or line.strip().startswith('#'):
                    continue

                if ':' in line and not line.strip().startswith('-'):
                    key, value = line.split(':', 1)
                    key = key.strip()
                    value = value.strip()

                    if value in ('null', ''):
                        data[key] = None
                    elif value == 'true':
                        data[key] = True
                    elif value == 'false':
                        data[key] = False
                    elif value.startswith('"') and value.endswith('"'):
                        data[key] = value[1:-1]
                    else:
                        data[key] = value

            return data

    yaml = SimpleYAML()


# ============================================================================
# CONFIGURATION
# ============================================================================

REPO_ROOT = Path(__file__).parent.parent.absolute()
OUTPUT_DIR = REPO_ROOT / "output"
SESSIONS_DIR = OUTPUT_DIR / "sessions"
SHARED_DIR = OUTPUT_DIR / "shared"
PROMOTED_DIR = SHARED_DIR / "promoted-to-confluence"


# ============================================================================
# UTILITIES
# ============================================================================

def get_git_user() -> Tuple[Optional[str], Optional[str]]:
    """Get git user info."""
    try:
        result = subprocess.run(
            ["git", "config", "user.name"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True
        )
        name = result.stdout.strip()

        result = subprocess.run(
            ["git", "config", "user.email"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True
        )
        email = result.stdout.strip()

        return name, email
    except Exception:
        return None, None


def parse_confluence_url(url: str) -> Optional[Dict[str, str]]:
    """
    Parse Confluence URL to extract space key and page ID.

    Expected format:
      https://company.atlassian.net/wiki/spaces/SPACE/pages/123456/Page+Title
    """
    # Pattern: .../spaces/{SPACE}/pages/{PAGE_ID}/...
    match = re.search(r'/spaces/([A-Z0-9]+)/pages/(\d+)', url, re.IGNORECASE)
    if match:
        space_key, page_id = match.groups()
        return {
            "space_key": space_key.upper(),
            "page_id": page_id,
            "url": url
        }
    return None


def find_session(session_id: str) -> Optional[Path]:
    """Find session directory by ID."""
    if not SESSIONS_DIR.exists():
        return None

    for user_dir in SESSIONS_DIR.iterdir():
        if not user_dir.is_dir():
            continue

        session_dir = user_dir / session_id
        if session_dir.exists() and session_dir.is_dir():
            return session_dir

    return None


def load_session_metadata(session_dir: Path) -> Optional[Dict]:
    """Load session metadata."""
    metadata_path = session_dir / ".session-metadata.yaml"
    if not metadata_path.exists():
        return None

    try:
        with open(metadata_path, 'r') as f:
            return yaml.safe_load(f)
    except Exception as e:
        print(f"Error loading metadata: {e}", file=sys.stderr)
        return None


def save_session_metadata(session_dir: Path, metadata: Dict) -> bool:
    """Save session metadata."""
    metadata_path = session_dir / ".session-metadata.yaml"
    try:
        with open(metadata_path, 'w') as f:
            yaml.dump(metadata, f)
        return True
    except Exception as e:
        print(f"Error saving metadata: {e}", file=sys.stderr)
        return False


def create_promotion_metadata(
    source_session_id: str,
    source_user: str,
    source_file: str,
    source_agent: str,
    confluence_info: Dict,
    promoted_by_name: str,
    promoted_by_email: str,
    notify: Optional[str]
) -> Dict:
    """Create promotion metadata."""
    now = datetime.utcnow()

    metadata = {
        "promoted_at": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "promoted_by": {
            "user": promoted_by_name,
            "email": promoted_by_email
        },
        "source": {
            "session_id": source_session_id,
            "user": source_user,
            "file": source_file,
            "agent": source_agent
        },
        "confluence": {
            "space_key": confluence_info["space_key"],
            "page_id": confluence_info["page_id"],
            "page_url": confluence_info["url"]
        },
        "notified": notify.split(',') if notify else [],
        "notes": """This output has been manually promoted to Confluence.

The content was reviewed, enhanced for Confluence formatting,
and manually copied to the Confluence page.

This metadata tracks the promotion for audit and search purposes.
"""
    }

    return metadata


# ============================================================================
# PROMOTION LOGIC
# ============================================================================

def promote_output(
    session_id: str,
    file_path: str,
    confluence_url: str,
    notify: Optional[str]
) -> int:
    """Promote an output to Confluence."""

    print("=" * 70)
    print("CONFLUENCE PROMOTION")
    print("=" * 70)
    print()

    # Get git user
    git_name, git_email = get_git_user()
    if not git_name or not git_email:
        print("❌ Git user not configured")
        return 1

    # Parse Confluence URL
    confluence_info = parse_confluence_url(confluence_url)
    if not confluence_info:
        print(f"❌ Invalid Confluence URL format: {confluence_url}")
        print()
        print("Expected format:")
        print("  https://company.atlassian.net/wiki/spaces/SPACE/pages/123456/Page+Title")
        return 1

    space_key = confluence_info["space_key"]
    page_id = confluence_info["page_id"]

    print(f"🔍 Looking for session: {session_id}")

    # Find session
    session_dir = find_session(session_id)
    if not session_dir:
        print(f"❌ Session not found: {session_id}")
        return 1

    print(f"   ✅ Found: {session_dir}")
    print()

    # Load session metadata
    metadata = load_session_metadata(session_dir)
    if not metadata:
        print("❌ Failed to load session metadata")
        return 1

    # Check if file exists in session
    source_file = session_dir / file_path
    if not source_file.exists():
        print(f"❌ File not found in session: {file_path}")
        print(f"   Looked in: {source_file}")
        return 1

    print(f"📄 Source file: {file_path}")
    print(f"🔗 Confluence: {space_key}/pages/{page_id}")
    print()

    # Determine agent from metadata
    agent = "unknown"
    for output in metadata.get("outputs", []):
        if output.get("file") == file_path:
            agent = output.get("agent", "unknown")
            break

    # Create promoted directory structure
    promoted_space_dir = PROMOTED_DIR / space_key
    promoted_page_dir = promoted_space_dir / page_id
    promoted_page_dir.mkdir(parents=True, exist_ok=True)

    # Copy file to promoted directory
    dest_file = promoted_page_dir / source_file.name
    try:
        shutil.copy2(source_file, dest_file)
        print(f"✅ Copied to: {dest_file}")
    except Exception as e:
        print(f"❌ Failed to copy file: {e}")
        return 1

    # Create promotion metadata
    promotion_metadata = create_promotion_metadata(
        source_session_id=session_id,
        source_user=session_dir.parent.name,
        source_file=file_path,
        source_agent=agent,
        confluence_info=confluence_info,
        promoted_by_name=git_name,
        promoted_by_email=git_email,
        notify=notify
    )

    promotion_metadata_path = promoted_page_dir / ".promotion-metadata.yaml"
    try:
        with open(promotion_metadata_path, 'w') as f:
            yaml.dump(promotion_metadata, f)
        print(f"✅ Promotion metadata: {promotion_metadata_path}")
    except Exception as e:
        print(f"❌ Failed to write promotion metadata: {e}")
        return 1

    # Update session metadata
    updated = False
    for output in metadata.get("outputs", []):
        if output.get("file") == file_path:
            output["promoted"] = True
            output["promoted_to"] = confluence_url
            updated = True
            break

    if updated:
        if save_session_metadata(session_dir, metadata):
            print(f"✅ Session metadata updated")
        else:
            print(f"⚠️  Failed to update session metadata")
    else:
        print(f"⚠️  Output not found in session metadata")

    print()
    print("=" * 70)
    print("PROMOTION COMPLETE")
    print("=" * 70)
    print()
    print(f"✅ Output promoted successfully!")
    print()
    print(f"📋 Promoted file: {dest_file}")
    print(f"📝 Metadata: {promotion_metadata_path}")
    print(f"🔗 Confluence: {confluence_url}")
    print()

    if notify:
        print(f"📧 Notifications tracked for: {notify}")
        print("   (Email sending not implemented - manual notification required)")
        print()

    print("Next Steps:")
    print("  1. The file has been copied to shared/promoted-to-confluence/")
    print("  2. Manually copy/paste content to Confluence page")
    print("  3. Enhance formatting for Confluence (macros, @mentions, etc.)")
    print("  4. Notify stakeholders as needed")
    print("  5. Commit promotion metadata to git")
    print()

    return 0


# ============================================================================
# CLI INTERFACE
# ============================================================================

def main():
    """Main CLI interface."""
    parser = argparse.ArgumentParser(
        description="Track manual Confluence promotions",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Promote an output to Confluence
  %(prog)s \\
    --session 2025-11-22_feature-invoice-automation_a3f42c \\
    --file analysis/2025-11-22_06-58-38_invoice-process-analysis_cs-business-analyst.md \\
    --confluence-url "https://company.atlassian.net/wiki/spaces/PROJ/pages/123456"

  # With notifications
  %(prog)s \\
    --session 2025-11-22_feature-invoice-automation_a3f42c \\
    --file analysis/invoice-analysis.md \\
    --confluence-url "https://company.atlassian.net/wiki/spaces/PROJ/pages/123456" \\
    --notify "sarah@company.com,mike@company.com"
"""
    )

    parser.add_argument("--session", required=True,
                       help="Session ID containing the output")
    parser.add_argument("--file", required=True,
                       help="File path relative to session directory (e.g., analysis/file.md)")
    parser.add_argument("--confluence-url", required=True,
                       help="Full Confluence page URL")
    parser.add_argument("--notify",
                       help="Comma-separated email addresses to notify (tracking only)")

    args = parser.parse_args()

    return promote_output(
        session_id=args.session,
        file_path=args.file,
        confluence_url=args.confluence_url,
        notify=args.notify
    )


if __name__ == "__main__":
    sys.exit(main())
